[tools]
elixir = "latest"
erlang = "latest"
node = "lts"
odin = "latest"
usage = "latest"
watchexec = "latest"

[tool_alias]
m = "mise"

[settings]
experimental = true

[settings.node]
gpg_verify = false
